#!/bin/bash

dat=$(date +%H%M%p)
hr=${dat:0:2}
mn=$((10#${dat:2:2}))
ap=${dat:4:2}

if [ "$#" -ne "0" ]; then
	echo "Ignoring everything after command and telling system time..."
fi

hours=("twelve" "one" "two" "three" "four" "five" "six" "seven" "eight" "nine" "ten" "eleven")
tens=(" oh" "" " twenty" " thirty" " forty" " fifty")
ones=("clock" "one" "two" "three" "four" "five" "six" "seven" "eight" "nine" "ten" "eleven" "twelve" "thirteen" "fourteen" "fifteen" "sixteen" "seventeen" "eighteen" "nineteen")

if (( $(($mn/10)) > 1 )) && (( $(($mn%10)) == 0 )); then
	teen=""
elif (( $(($mn/10)) == 1 )); then
	teen=" ${ones[$(($mn%20))]}"
else
	teen=" ${ones[$(($mn%10))]}"
fi

echo "It's ${hours[$(($hr%12))]}${tens[$(($mn/10))]}$teen $ap"
